name: Release Webman Feature

on:
  workflow_dispatch:
  push:
    tags:
      - "webman-net-tools-v*"

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish devcontainer feature
        uses: devcontainers/action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          devcontainer-cli-version: "0.65.0"
